#!/usr/bin/env python3
import csv
import sys
import subprocess
import os
from datetime import datetime

def ensure_dependencies():
    """Verify fpdf is installed, prompt if missing."""
    try:
        import fpdf
    except ImportError:
        print("\n[!] FPDF library is missing.")
        ans = input("Would you like to install it now? [y/N]: ").strip().lower()
        if ans in ['y', 'yes']:
            print("[*] Installing fpdf...")
            subprocess.run([sys.executable, "-m", "pip", "install", "fpdf", "--break-system-packages"])

               # Re-import after install

            import fpdf
        else:
            print("[-] Cannot generate PDF without fpdf. Exiting.")
            sys.exit(1)
              
# Run this immediately

ensure_dependencies()

# NOW you can safely import FPDF

from fpdf import FPDF

# =======================================================================
# [+] ENHANCEMENT: AUTOMATED PDF REPORT GENERATOR WITH COLOR DASHBOARD
# =======================================================================

class PDFReport(FPDF):
    def header(self):
        current_date = datetime.now().strftime("%B %d, %Y")
        
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "Automated Vulnerability Assessment Report", ln=True, align="C")
        self.set_font("Arial", "I", 10)
        self.cell(0, 6, "Generated by The Scripting Syndicate", ln=True, align="C")
        self.set_font("Arial", "", 10)
        self.cell(0, 6, f"Date: {current_date}", ln=True, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def get_severity_color(label):
    label = label.upper()
    if label == "CRITICAL": return (200, 0, 0)      # Dark Red
    if label == "HIGH":     return (255, 0, 0)      # Bright Red
    if label == "MEDIUM":   return (200, 150, 0)    # Dark Yellow/Orange
    if label == "LOW":      return (0, 150, 0)      # Green
    return (128, 128, 128)                          # Gray for NONE/Unknown

def draw_dashboard(pdf, stats):
    pdf.set_fill_color(245, 245, 245) # Light gray background
    pdf.set_font("Arial", "B", 12)
    
    pdf.cell(0, 10, " EXECUTION SUMMARY", border=1, ln=True, fill=True)
    pdf.set_font("Arial", "", 11)
    
    pdf.cell(60, 8, " Target:", border="L")
    pdf.cell(0, 8, stats['target'], border="R", ln=True)
    
    pdf.cell(60, 8, " Total Open Services:", border="L")
    pdf.cell(0, 8, stats['total_svc'], border="R", ln=True)
    
    pdf.cell(60, 8, " Vulnerable Services:", border="L")
    pdf.cell(0, 8, stats['vuln_svc'], border="R", ln=True)
    
    pdf.cell(60, 8, " Total CVEs Found:", border="L")
    pdf.cell(0, 8, stats['total_cves'], border="R", ln=True)
    
    pdf.cell(60, 8, " Highest Severity:", border="L")
    r, g, b = get_severity_color(stats['label'])
    pdf.set_text_color(r, g, b)
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, f"{stats['label']} ({stats['top_score']}/10)", border="R", ln=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)

    # CISA KEV row - red the moment count > 0, since even one actively
    # exploited CVE changes the priority of the whole report.

    pdf.cell(60, 8, " CISA KEV Matches:", border="L")
    kev_count = stats.get('kev_count', '0')
    if int(kev_count) > 0:
        pdf.set_text_color(200, 0, 0)
        pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, kev_count, border="R", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)

    pdf.cell(60, 8, " Execution Time:", border="L, B")
    pdf.cell(0, 8, f"{stats['runtime']} seconds", border="R, B", ln=True)
    pdf.ln(10)

def generate_pdf(csv_file, pdf_file, stats):
    if not os.path.exists(csv_file):
        print(f"[-] Error: Could not find '{csv_file}'.")
        sys.exit(1)

    # Read the CSV first so we can fold the CISA KEV count into the dashboard
    # stats before drawing it - the CSV already carries a "CISA KEV" column
    # per row from threat_intel.py, so no extra lookup is needed here.

    findings = []
    with open(csv_file, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            findings.append(row)

    stats['kev_count'] = str(sum(1 for f in findings if f.get("CISA KEV") == "Yes"))

    pdf = PDFReport()
    pdf.add_page()

    draw_dashboard(pdf, stats)

    if not findings:
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Scan completed successfully. No vulnerabilities identified.", ln=True)
    else:
        targets = set(f["Target"] for f in findings if "Target" in f)
        for target in targets:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, f"Detailed Findings: {target}", ln=True)
            pdf.ln(2)
            
            pdf.set_font("Arial", size=11)
            pdf.multi_cell(0, 7, f"The machine at {target} was scanned. The following open ports and services were discovered, along with any known CVE vulnerabilities. Services marked as 'None - Clean' have no known immediate threats.")
            pdf.ln(5)

            # Column widths for a 190mm usable page width:
            # Port(18) + Service(32) + CVE ID(30) + Score(16) + KEV(14) + Remediation(80) = 190

            pdf.set_font("Arial", "B", 9)
            pdf.cell(18, 8, "Port", border=1, align="C")
            pdf.cell(32, 8, "Service", border=1, align="C")
            pdf.cell(30, 8, "CVE ID", border=1, align="C")
            pdf.cell(16, 8, "Score", border=1, align="C")
            pdf.cell(14, 8, "KEV", border=1, align="C")
            pdf.cell(80, 8, "Remediation", border=1, align="C")
            pdf.ln()

            pdf.set_font("Arial", size=9)
            target_findings = [f for f in findings if f.get("Target") == target]
            for finding in target_findings:
                is_kev = finding.get("CISA KEV", "No") == "Yes"

                pdf.cell(18, 8, finding.get("Port", "N/A"), border=1, align="C")
                pdf.cell(32, 8, finding.get("Service", "N/A"), border=1, align="C")
                pdf.cell(30, 8, finding.get("CVE ID", "N/A"), border=1, align="C")
                pdf.cell(16, 8, finding.get("CVSS Score", "N/A"), border=1, align="C")

                # Flag KEV matches in red so they stand out in the printed table

                if is_kev:
                    pdf.set_text_color(200, 0, 0)
                    pdf.set_font("Arial", "B", 9)
                pdf.cell(14, 8, "Yes" if is_kev else "No", border=1, align="C")
                pdf.set_text_color(0, 0, 0)
                pdf.set_font("Arial", size=9)

                # Truncate remediation text slightly if it's too long for the cell width

                rem_text = finding.get("Remediation Guidance", "Review vendor patch notes.")
                if len(rem_text) > 48:
                    rem_text = rem_text[:45] + "..."
                pdf.cell(80, 8, rem_text, border=1, align="L")
                pdf.ln()
            pdf.ln(5)

    # Team Roster

    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Report verified and generated by The Scripting Syndicate:", ln=True)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 7, "- Devon Brown (Project Lead & Developer)", ln=True)
    pdf.cell(0, 7, "- Shannika Dyer (Documentarian)", ln=True)
    pdf.cell(0, 7, "- Adam Timmons (Tester)", ln=True)
    pdf.cell(0, 7, "- Edy Silveira de Souza (Presenter)", ln=True)

    # Executive-friendly report footer (e.g., July 15, 2026 at 02:30 PM)

    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p (Local Time)")
    pdf.ln(5)
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 7, f"Official scan concluded on: {timestamp}", ln=True)

    pdf.output(pdf_file)
    print(f"[+] Executive Report successfully generated: {pdf_file}")

if __name__ == "__main__":
    stats = {
        'target': sys.argv[1] if len(sys.argv) > 1 else "Unknown",
        'total_svc': sys.argv[2] if len(sys.argv) > 2 else "0",
        'vuln_svc': sys.argv[3] if len(sys.argv) > 3 else "0",
        'total_cves': sys.argv[4] if len(sys.argv) > 4 else "0",
        'top_score': sys.argv[5] if len(sys.argv) > 5 else "0.0",
        'label': sys.argv[6] if len(sys.argv) > 6 else "NONE",
        'runtime': sys.argv[7] if len(sys.argv) > 7 else "0.0"
    }
    
    # Catch the dynamic filenames passed from threat_intel.py
    
    INPUT_CSV = sys.argv[8] if len(sys.argv) > 8 else "scan_report.csv"
    OUTPUT_PDF = sys.argv[9] if len(sys.argv) > 9 else "Executive_Vulnerability_Report.pdf"
    
    generate_pdf(INPUT_CSV, OUTPUT_PDF, stats)