[API_ENDPOINTS]
#CIRCL open source API for CVE details
circl_url = https://cve.circl.lu/api/cve/
# NIST API for CVSS scores
nist_url = https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=
# NIST API Key for added requests
nist_api_key = c0ebeb30-b8ca-425e-b15b-90784704a039

[THRESHOLDS]
#CVSS score that triggers a "CRITICAL" alert
critical_cvss_score = 9.0
high_cvss_score = 7.0